[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "dexsnake"
version = "0.0.1"
dependencies = ["web3>=7,<8"]
authors = [
  { name="Leevi Kerkelä", email="leevi.kerkela@protonmail.com" },
]
description = "A Python package for trading on decentralized exchanges like Uniswap."
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/kerkelae/dexsnake"

[tool.setuptools.package-data]
"dexsnake.uniswap_v2" = ["abi/*.json"]
"dexsnake.uniswap_v3" = ["abi/*.json"]
"dexsnake.utils" = ["abi/*.json"]

[tool.pytest.ini_options]
markers = ["fork: tests using a local Anvil fork"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
